name: pre-commit

on:
  push:
    branches: [main,]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create folders
        run: |
          mkdir -p artifact/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Linting
        run: |
            pre-commit run trailing-whitespace --all-files
            pre-commit run double-quote-string-fixer --all-files
            pre-commit run black --all-files
            pre-commit run flake8 --all-files

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact/

#  notify:
#    runs-on: ubuntu-latest
#    needs: linting
#    steps:
#      - name: send telegram message
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ${{ github.actor }} created commit:
#            Commit message: ${{ github.event.commits[0].message }}
#
#            Repository: ${{ github.repository }}
#
#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

